// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: Nitro.CodeFragment
#include "Nitro/CodeFragment.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: Nitro
namespace Nitro {
  // Forward declaring type: BracketFragment
  class BracketFragment;
  // Forward declaring type: CompiledFragment
  class CompiledFragment;
  // Forward declaring type: CompiledMethod
  class CompiledMethod;
}
// Completed forward declares
// Type namespace: Nitro
namespace Nitro {
  // Forward declaring type: ObjectFragment
  class ObjectFragment;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::Nitro::ObjectFragment);
DEFINE_IL2CPP_ARG_TYPE(::Nitro::ObjectFragment*, "Nitro", "ObjectFragment");
// Type namespace: Nitro
namespace Nitro {
  // Size: 0x48
  #pragma pack(push, 1)
  // Autogenerated type: Nitro.ObjectFragment
  // [TokenAttribute] Offset: FFFFFFFF
  class ObjectFragment : public ::Nitro::CodeFragment {
    public:
    public:
    // public Nitro.BracketFragment Contents
    // Size: 0x8
    // Offset: 0x40
    ::Nitro::BracketFragment* Contents;
    // Field size check
    static_assert(sizeof(::Nitro::BracketFragment*) == 0x8);
    public:
    // Creating conversion operator: operator ::Nitro::BracketFragment*
    constexpr operator ::Nitro::BracketFragment*() const noexcept {
      return Contents;
    }
    // Get instance field reference: public Nitro.BracketFragment Contents
    [[deprecated("Use field access instead!")]] ::Nitro::BracketFragment*& dyn_Contents();
    // public System.Void .ctor(Nitro.BracketFragment contents)
    // Offset: 0x16E1228
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static ObjectFragment* New_ctor(::Nitro::BracketFragment* contents) {
      static auto ___internal__logger = ::Logger::get().WithContext("::Nitro::ObjectFragment::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<ObjectFragment*, creationType>(contents)));
    }
    // public override Nitro.CompiledFragment Compile(Nitro.CompiledMethod parent)
    // Offset: 0x16E1260
    // Implemented from: Nitro.CodeFragment
    // Base method: Nitro.CompiledFragment CodeFragment::Compile(Nitro.CompiledMethod parent)
    ::Nitro::CompiledFragment* Compile(::Nitro::CompiledMethod* parent);
    // public override System.String ToString()
    // Offset: 0x16E1268
    // Implemented from: Nitro.CodeFragment
    // Base method: System.String CodeFragment::ToString()
    ::StringW ToString();
  }; // Nitro.ObjectFragment
  #pragma pack(pop)
  static check_size<sizeof(ObjectFragment), 64 + sizeof(::Nitro::BracketFragment*)> __Nitro_ObjectFragmentSizeCheck;
  static_assert(sizeof(ObjectFragment) == 0x48);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: Nitro::ObjectFragment::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: Nitro::ObjectFragment::Compile
// Il2CppName: Compile
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::Nitro::CompiledFragment* (Nitro::ObjectFragment::*)(::Nitro::CompiledMethod*)>(&Nitro::ObjectFragment::Compile)> {
  static const MethodInfo* get() {
    static auto* parent = &::il2cpp_utils::GetClassFromName("Nitro", "CompiledMethod")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Nitro::ObjectFragment*), "Compile", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{parent});
  }
};
// Writing MetadataGetter for method: Nitro::ObjectFragment::ToString
// Il2CppName: ToString
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (Nitro::ObjectFragment::*)()>(&Nitro::ObjectFragment::ToString)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(Nitro::ObjectFragment*), "ToString", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
