// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: Pathfinding.GraphModifier
#include "Pathfinding/GraphModifier.hpp"
// Including type: System.Enum
#include "System/Enum.hpp"
// Completed includes
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(::Pathfinding::GraphModifier::EventType, "Pathfinding", "GraphModifier/EventType");
// Type namespace: Pathfinding
namespace Pathfinding {
  // Size: 0x4
  #pragma pack(push, 1)
  // Autogenerated type: Pathfinding.GraphModifier/EventType
  // [TokenAttribute] Offset: FFFFFFFF
  struct GraphModifier::EventType/*, public ::System::Enum*/ {
    public:
    public:
    // public System.Int32 value__
    // Size: 0x4
    // Offset: 0x0
    int value;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    public:
    // Creating value type constructor for type: EventType
    constexpr EventType(int value_ = {}) noexcept : value{value_} {}
    // Creating interface conversion operator: operator ::System::Enum
    operator ::System::Enum() noexcept {
      return *reinterpret_cast<::System::Enum*>(this);
    }
    // Creating conversion operator: operator int
    constexpr operator int() const noexcept {
      return value;
    }
    // static field const value: static public Pathfinding.GraphModifier/EventType PostScan
    static constexpr const int PostScan = 1;
    // Get static field: static public Pathfinding.GraphModifier/EventType PostScan
    static ::Pathfinding::GraphModifier::EventType _get_PostScan();
    // Set static field: static public Pathfinding.GraphModifier/EventType PostScan
    static void _set_PostScan(::Pathfinding::GraphModifier::EventType value);
    // static field const value: static public Pathfinding.GraphModifier/EventType PreScan
    static constexpr const int PreScan = 2;
    // Get static field: static public Pathfinding.GraphModifier/EventType PreScan
    static ::Pathfinding::GraphModifier::EventType _get_PreScan();
    // Set static field: static public Pathfinding.GraphModifier/EventType PreScan
    static void _set_PreScan(::Pathfinding::GraphModifier::EventType value);
    // static field const value: static public Pathfinding.GraphModifier/EventType LatePostScan
    static constexpr const int LatePostScan = 4;
    // Get static field: static public Pathfinding.GraphModifier/EventType LatePostScan
    static ::Pathfinding::GraphModifier::EventType _get_LatePostScan();
    // Set static field: static public Pathfinding.GraphModifier/EventType LatePostScan
    static void _set_LatePostScan(::Pathfinding::GraphModifier::EventType value);
    // static field const value: static public Pathfinding.GraphModifier/EventType PreUpdate
    static constexpr const int PreUpdate = 8;
    // Get static field: static public Pathfinding.GraphModifier/EventType PreUpdate
    static ::Pathfinding::GraphModifier::EventType _get_PreUpdate();
    // Set static field: static public Pathfinding.GraphModifier/EventType PreUpdate
    static void _set_PreUpdate(::Pathfinding::GraphModifier::EventType value);
    // static field const value: static public Pathfinding.GraphModifier/EventType PostUpdate
    static constexpr const int PostUpdate = 16;
    // Get static field: static public Pathfinding.GraphModifier/EventType PostUpdate
    static ::Pathfinding::GraphModifier::EventType _get_PostUpdate();
    // Set static field: static public Pathfinding.GraphModifier/EventType PostUpdate
    static void _set_PostUpdate(::Pathfinding::GraphModifier::EventType value);
    // static field const value: static public Pathfinding.GraphModifier/EventType PostCacheLoad
    static constexpr const int PostCacheLoad = 32;
    // Get static field: static public Pathfinding.GraphModifier/EventType PostCacheLoad
    static ::Pathfinding::GraphModifier::EventType _get_PostCacheLoad();
    // Set static field: static public Pathfinding.GraphModifier/EventType PostCacheLoad
    static void _set_PostCacheLoad(::Pathfinding::GraphModifier::EventType value);
    // Get instance field reference: public System.Int32 value__
    [[deprecated("Use field access instead!")]] int& dyn_value__();
  }; // Pathfinding.GraphModifier/EventType
  #pragma pack(pop)
  static check_size<sizeof(GraphModifier::EventType), 0 + sizeof(int)> __Pathfinding_GraphModifier_EventTypeSizeCheck;
  static_assert(sizeof(GraphModifier::EventType) == 0x4);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
