// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: MagicalActual.Bard
#include "MagicalActual/Bard.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::IO
namespace System::IO {
  // Forward declaring type: BinaryWriter
  class BinaryWriter;
}
// Completed forward declares
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::MagicalActual::Bard::$$c__DisplayClass135_0);
DEFINE_IL2CPP_ARG_TYPE(::MagicalActual::Bard::$$c__DisplayClass135_0*, "MagicalActual", "Bard/<>c__DisplayClass135_0");
// Type namespace: MagicalActual
namespace MagicalActual {
  // Size: 0x14
  #pragma pack(push, 1)
  // Autogenerated type: MagicalActual.Bard/<>c__DisplayClass135_0
  // [TokenAttribute] Offset: FFFFFFFF
  // [CompilerGeneratedAttribute] Offset: AD2CC4
  class Bard::$$c__DisplayClass135_0 : public ::Il2CppObject {
    public:
    public:
    // public System.Int32 GFCOFEOGIDM
    // Size: 0x4
    // Offset: 0x10
    int GFCOFEOGIDM;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    public:
    // Creating conversion operator: operator int
    constexpr operator int() const noexcept {
      return GFCOFEOGIDM;
    }
    // Get instance field reference: public System.Int32 GFCOFEOGIDM
    [[deprecated("Use field access instead!")]] int& dyn_GFCOFEOGIDM();
    // System.Void AHIPDIAJDEC(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99150
    void AHIPDIAJDEC(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void KHBKDPIBDCL(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99190
    void KHBKDPIBDCL(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void EIDPHKGLCIN(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C991D0
    void EIDPHKGLCIN(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void EAGCNNIOGLB(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99210
    void EAGCNNIOGLB(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void AFHKJONEHMK(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99250
    void AFHKJONEHMK(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void DCFLNAKFBMH(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99290
    void DCFLNAKFBMH(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void MGJJMBMKAIG(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C992D0
    void MGJJMBMKAIG(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void FBIDILEKPDG(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99310
    void FBIDILEKPDG(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void NDBMPBOCFHK(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99350
    void NDBMPBOCFHK(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void EJECBPLLJOE(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99390
    void EJECBPLLJOE(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void AFMBBJMCNFC(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C993D0
    void AFMBBJMCNFC(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void CMCLADEKCKL(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99410
    void CMCLADEKCKL(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void JJGLCNPCNJD(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99450
    void JJGLCNPCNJD(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void AENKHBMONAM(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99490
    void AENKHBMONAM(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void JFGKKJFNEPL(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C994D0
    void JFGKKJFNEPL(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void EACHPFKMNHI(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99510
    void EACHPFKMNHI(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void DHMDHJIACPG(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99550
    void DHMDHJIACPG(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void BPEKANNHHGB(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99590
    void BPEKANNHHGB(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void CEDLOHPICAM(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C995D0
    void CEDLOHPICAM(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void MBJNJPNJBJH(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99610
    void MBJNJPNJBJH(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void PBEKAMGBJDF(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99650
    void PBEKAMGBJDF(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void AOLJJGGPPGG(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99690
    void AOLJJGGPPGG(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void LHPDCKNKKEO(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C996D0
    void LHPDCKNKKEO(::System::IO::BinaryWriter* FFJEENIEPJH);
    // public System.Void .ctor()
    // Offset: 0x1C99710
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static Bard::$$c__DisplayClass135_0* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::MagicalActual::Bard::$$c__DisplayClass135_0::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<Bard::$$c__DisplayClass135_0*, creationType>()));
    }
    // System.Void NEKECLOFBDH(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99718
    void NEKECLOFBDH(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void IGBLHBEMNKK(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99758
    void IGBLHBEMNKK(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void BLPDBFPCDEG(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99798
    void BLPDBFPCDEG(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void PEOFHFJODPO(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C997D8
    void PEOFHFJODPO(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void PFFPGAHJELL(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99818
    void PFFPGAHJELL(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void NLNHAHNKEHI(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99858
    void NLNHAHNKEHI(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void IOJMFBNDKBI(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99898
    void IOJMFBNDKBI(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void AJCNGPLBIND(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C998D8
    void AJCNGPLBIND(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void MMADNGDFFBF(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1C99918
    void MMADNGDFFBF(::System::IO::BinaryWriter* FFJEENIEPJH);
  }; // MagicalActual.Bard/<>c__DisplayClass135_0
  #pragma pack(pop)
  static check_size<sizeof(Bard::$$c__DisplayClass135_0), 16 + sizeof(int)> __MagicalActual_Bard_$$c__DisplayClass135_0SizeCheck;
  static_assert(sizeof(Bard::$$c__DisplayClass135_0) == 0x14);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::AHIPDIAJDEC
// Il2CppName: AHIPDIAJDEC
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::AHIPDIAJDEC)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "AHIPDIAJDEC", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::KHBKDPIBDCL
// Il2CppName: KHBKDPIBDCL
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::KHBKDPIBDCL)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "KHBKDPIBDCL", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::EIDPHKGLCIN
// Il2CppName: EIDPHKGLCIN
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::EIDPHKGLCIN)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "EIDPHKGLCIN", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::EAGCNNIOGLB
// Il2CppName: EAGCNNIOGLB
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::EAGCNNIOGLB)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "EAGCNNIOGLB", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::AFHKJONEHMK
// Il2CppName: AFHKJONEHMK
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::AFHKJONEHMK)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "AFHKJONEHMK", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::DCFLNAKFBMH
// Il2CppName: DCFLNAKFBMH
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::DCFLNAKFBMH)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "DCFLNAKFBMH", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::MGJJMBMKAIG
// Il2CppName: MGJJMBMKAIG
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::MGJJMBMKAIG)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "MGJJMBMKAIG", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::FBIDILEKPDG
// Il2CppName: FBIDILEKPDG
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::FBIDILEKPDG)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "FBIDILEKPDG", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::NDBMPBOCFHK
// Il2CppName: NDBMPBOCFHK
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::NDBMPBOCFHK)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "NDBMPBOCFHK", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::EJECBPLLJOE
// Il2CppName: EJECBPLLJOE
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::EJECBPLLJOE)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "EJECBPLLJOE", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::AFMBBJMCNFC
// Il2CppName: AFMBBJMCNFC
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::AFMBBJMCNFC)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "AFMBBJMCNFC", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::CMCLADEKCKL
// Il2CppName: CMCLADEKCKL
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::CMCLADEKCKL)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "CMCLADEKCKL", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::JJGLCNPCNJD
// Il2CppName: JJGLCNPCNJD
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::JJGLCNPCNJD)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "JJGLCNPCNJD", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::AENKHBMONAM
// Il2CppName: AENKHBMONAM
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::AENKHBMONAM)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "AENKHBMONAM", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::JFGKKJFNEPL
// Il2CppName: JFGKKJFNEPL
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::JFGKKJFNEPL)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "JFGKKJFNEPL", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::EACHPFKMNHI
// Il2CppName: EACHPFKMNHI
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::EACHPFKMNHI)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "EACHPFKMNHI", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::DHMDHJIACPG
// Il2CppName: DHMDHJIACPG
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::DHMDHJIACPG)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "DHMDHJIACPG", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::BPEKANNHHGB
// Il2CppName: BPEKANNHHGB
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::BPEKANNHHGB)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "BPEKANNHHGB", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::CEDLOHPICAM
// Il2CppName: CEDLOHPICAM
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::CEDLOHPICAM)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "CEDLOHPICAM", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::MBJNJPNJBJH
// Il2CppName: MBJNJPNJBJH
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::MBJNJPNJBJH)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "MBJNJPNJBJH", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::PBEKAMGBJDF
// Il2CppName: PBEKAMGBJDF
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::PBEKAMGBJDF)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "PBEKAMGBJDF", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::AOLJJGGPPGG
// Il2CppName: AOLJJGGPPGG
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::AOLJJGGPPGG)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "AOLJJGGPPGG", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::LHPDCKNKKEO
// Il2CppName: LHPDCKNKKEO
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::LHPDCKNKKEO)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "LHPDCKNKKEO", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::NEKECLOFBDH
// Il2CppName: NEKECLOFBDH
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::NEKECLOFBDH)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "NEKECLOFBDH", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::IGBLHBEMNKK
// Il2CppName: IGBLHBEMNKK
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::IGBLHBEMNKK)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "IGBLHBEMNKK", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::BLPDBFPCDEG
// Il2CppName: BLPDBFPCDEG
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::BLPDBFPCDEG)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "BLPDBFPCDEG", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::PEOFHFJODPO
// Il2CppName: PEOFHFJODPO
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::PEOFHFJODPO)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "PEOFHFJODPO", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::PFFPGAHJELL
// Il2CppName: PFFPGAHJELL
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::PFFPGAHJELL)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "PFFPGAHJELL", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::NLNHAHNKEHI
// Il2CppName: NLNHAHNKEHI
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::NLNHAHNKEHI)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "NLNHAHNKEHI", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::IOJMFBNDKBI
// Il2CppName: IOJMFBNDKBI
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::IOJMFBNDKBI)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "IOJMFBNDKBI", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::AJCNGPLBIND
// Il2CppName: AJCNGPLBIND
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::AJCNGPLBIND)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "AJCNGPLBIND", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::Bard::$$c__DisplayClass135_0::MMADNGDFFBF
// Il2CppName: MMADNGDFFBF
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::Bard::$$c__DisplayClass135_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::Bard::$$c__DisplayClass135_0::MMADNGDFFBF)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::Bard::$$c__DisplayClass135_0*), "MMADNGDFFBF", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
