// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: MagicalActual.ItemContainer
#include "MagicalActual/ItemContainer.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Begin forward declares
// Forward declaring namespace: MagicalActual
namespace MagicalActual {
  // Forward declaring type: TransmogStation
  class TransmogStation;
}
// Forward declaring namespace: UnityEngine::Events
namespace UnityEngine::Events {
  // Forward declaring type: UnityEvent
  class UnityEvent;
}
// Completed forward declares
// Type namespace: MagicalActual
namespace MagicalActual {
  // Forward declaring type: CustomItemContainer
  class CustomItemContainer;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::MagicalActual::CustomItemContainer);
DEFINE_IL2CPP_ARG_TYPE(::MagicalActual::CustomItemContainer*, "MagicalActual", "CustomItemContainer");
// Type namespace: MagicalActual
namespace MagicalActual {
  // Size: 0x80
  #pragma pack(push, 1)
  // Autogenerated type: MagicalActual.CustomItemContainer
  // [TokenAttribute] Offset: FFFFFFFF
  class CustomItemContainer : public ::MagicalActual::ItemContainer {
    public:
    // Writing base type padding for base size: 0x64 to desired offset: 0x68
    char ___base_padding[0x4] = {};
    public:
    // private MagicalActual.TransmogStation station
    // Size: 0x8
    // Offset: 0x68
    ::MagicalActual::TransmogStation* station;
    // Field size check
    static_assert(sizeof(::MagicalActual::TransmogStation*) == 0x8);
    // private UnityEngine.Events.UnityEvent OnOpenContainerInventory
    // Size: 0x8
    // Offset: 0x70
    ::UnityEngine::Events::UnityEvent* OnOpenContainerInventory;
    // Field size check
    static_assert(sizeof(::UnityEngine::Events::UnityEvent*) == 0x8);
    // private UnityEngine.Events.UnityEvent OnCloseContainerInventory
    // Size: 0x8
    // Offset: 0x78
    ::UnityEngine::Events::UnityEvent* OnCloseContainerInventory;
    // Field size check
    static_assert(sizeof(::UnityEngine::Events::UnityEvent*) == 0x8);
    public:
    // Get instance field reference: private MagicalActual.TransmogStation station
    [[deprecated("Use field access instead!")]] ::MagicalActual::TransmogStation*& dyn_station();
    // Get instance field reference: private UnityEngine.Events.UnityEvent OnOpenContainerInventory
    [[deprecated("Use field access instead!")]] ::UnityEngine::Events::UnityEvent*& dyn_OnOpenContainerInventory();
    // Get instance field reference: private UnityEngine.Events.UnityEvent OnCloseContainerInventory
    [[deprecated("Use field access instead!")]] ::UnityEngine::Events::UnityEvent*& dyn_OnCloseContainerInventory();
    // protected System.Void FGGKEEKHDHN()
    // Offset: 0x19B21D8
    void FGGKEEKHDHN();
    // public System.Void GKBNFJNKHML()
    // Offset: 0x19B235C
    void GKBNFJNKHML();
    // public System.Void BDBBKHDEPKF()
    // Offset: 0x19B24F4
    void BDBBKHDEPKF();
    // public System.Void GJEFJHOPNKE()
    // Offset: 0x19B24F8
    void GJEFJHOPNKE();
    // public System.Void OFCINDGPKJB()
    // Offset: 0x19B2558
    void OFCINDGPKJB();
    // protected System.Void ICFANEFPFBJ()
    // Offset: 0x19B2588
    void ICFANEFPFBJ();
    // public System.Void BJMIBFKAICF()
    // Offset: 0x19B270C
    void BJMIBFKAICF();
    // protected System.Void HHKOFMNJKDA()
    // Offset: 0x19B2710
    void HHKOFMNJKDA();
    // public System.Void ODEEKFKBKMD()
    // Offset: 0x19B2894
    void ODEEKFKBKMD();
    // public System.Void EHHCJJADDDH()
    // Offset: 0x19B2898
    void EHHCJJADDDH();
    // public System.Void NHNOABLHEEJ()
    // Offset: 0x19B28C8
    void NHNOABLHEEJ();
    // public System.Void KCFODGDFLHL()
    // Offset: 0x19B28CC
    void KCFODGDFLHL();
    // protected System.Void LLMONLBCLKC()
    // Offset: 0x19B292C
    void LLMONLBCLKC();
    // protected System.Void HAPOEOFLCFC()
    // Offset: 0x19B2934
    void HAPOEOFLCFC();
    // public System.Void AOCHBOFKAKN()
    // Offset: 0x19B293C
    void AOCHBOFKAKN();
    // protected System.Void PJOIJIEDPMP()
    // Offset: 0x19B296C
    void PJOIJIEDPMP();
    // public System.Void GCCKLLDCHKL()
    // Offset: 0x19B2AF0
    void GCCKLLDCHKL();
    // protected System.Void HABDJCEKMNH()
    // Offset: 0x19B2B24
    void HABDJCEKMNH();
    // public System.Void HDDLOBOJCDD()
    // Offset: 0x19B2CA8
    void HDDLOBOJCDD();
    // public System.Void NBBNHDOBADH()
    // Offset: 0x19B2CD8
    void NBBNHDOBADH();
    // protected System.Void EFEDNMKDDGH()
    // Offset: 0x19B2CDC
    void EFEDNMKDDGH();
    // public System.Void MPKPGNJNLBO()
    // Offset: 0x19B2E60
    void MPKPGNJNLBO();
    // public System.Void FOIKDPOMLLN()
    // Offset: 0x19B2E64
    void FOIKDPOMLLN();
    // public System.Void HCILFCAANII()
    // Offset: 0x19B2E94
    void HCILFCAANII();
    // public System.Void ENNBLNMHCDM()
    // Offset: 0x19B2EC4
    void ENNBLNMHCDM();
    // public System.Void PMOIBHEEPKD()
    // Offset: 0x19B2EF4
    void PMOIBHEEPKD();
    // public System.Void PGDINKGGFHI()
    // Offset: 0x19B2F28
    void PGDINKGGFHI();
    // protected System.Void JPHEBENNLCB()
    // Offset: 0x19B2F58
    void JPHEBENNLCB();
    // protected System.Void GGAFMPPDBOH()
    // Offset: 0x19B30DC
    void GGAFMPPDBOH();
    // public System.Void KFFLHHLFGID()
    // Offset: 0x19B3260
    void KFFLHHLFGID();
    // public System.Void KLKNBEHJMLP()
    // Offset: 0x19B3290
    void KLKNBEHJMLP();
    // protected System.Void FMCOMKPJIML()
    // Offset: 0x19B3294
    void FMCOMKPJIML();
    // public System.Void .ctor()
    // Offset: 0x19B2360
    // Implemented from: MagicalActual.ItemContainer
    // Base method: System.Void ItemContainer::.ctor()
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static CustomItemContainer* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::MagicalActual::CustomItemContainer::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<CustomItemContainer*, creationType>()));
    }
    // protected override System.Void MMBJIKNCNGM()
    // Offset: 0x19B2368
    // Implemented from: MagicalActual.ItemContainer
    // Base method: System.Void ItemContainer::MMBJIKNCNGM()
    void MMBJIKNCNGM();
    // public override System.Void DetachedFromInterface()
    // Offset: 0x19B2370
    // Implemented from: MagicalActual.ItemContainer
    // Base method: System.Void ItemContainer::DetachedFromInterface()
    void DetachedFromInterface();
    // protected override System.Void FixedUpdate()
    // Offset: 0x19B2374
    // Implemented from: MagicalActual.ItemContainer
    // Base method: System.Void ItemContainer::FixedUpdate()
    void FixedUpdate();
    // public override System.Void OpenContainerInventory()
    // Offset: 0x19B2528
    // Implemented from: MagicalActual.ItemContainer
    // Base method: System.Void ItemContainer::OpenContainerInventory()
    void OpenContainerInventory();
    // public override System.Void CloseContainerInventory()
    // Offset: 0x19B28FC
    // Implemented from: MagicalActual.ItemContainer
    // Base method: System.Void ItemContainer::CloseContainerInventory()
    void CloseContainerInventory();
    // public override System.Void HICFANHNBBI()
    // Offset: 0x19B2B20
    // Implemented from: MagicalActual.ItemContainer
    // Base method: System.Void ItemContainer::HICFANHNBBI()
    void HICFANHNBBI();
    // public override System.Void AttachedToInterface()
    // Offset: 0x19B2F24
    // Implemented from: MagicalActual.ItemContainer
    // Base method: System.Void ItemContainer::AttachedToInterface()
    void AttachedToInterface();
  }; // MagicalActual.CustomItemContainer
  #pragma pack(pop)
  static check_size<sizeof(CustomItemContainer), 120 + sizeof(::UnityEngine::Events::UnityEvent*)> __MagicalActual_CustomItemContainerSizeCheck;
  static_assert(sizeof(CustomItemContainer) == 0x80);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::FGGKEEKHDHN
// Il2CppName: FGGKEEKHDHN
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::FGGKEEKHDHN)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "FGGKEEKHDHN", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::GKBNFJNKHML
// Il2CppName: GKBNFJNKHML
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::GKBNFJNKHML)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "GKBNFJNKHML", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::BDBBKHDEPKF
// Il2CppName: BDBBKHDEPKF
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::BDBBKHDEPKF)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "BDBBKHDEPKF", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::GJEFJHOPNKE
// Il2CppName: GJEFJHOPNKE
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::GJEFJHOPNKE)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "GJEFJHOPNKE", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::OFCINDGPKJB
// Il2CppName: OFCINDGPKJB
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::OFCINDGPKJB)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "OFCINDGPKJB", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::ICFANEFPFBJ
// Il2CppName: ICFANEFPFBJ
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::ICFANEFPFBJ)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "ICFANEFPFBJ", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::BJMIBFKAICF
// Il2CppName: BJMIBFKAICF
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::BJMIBFKAICF)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "BJMIBFKAICF", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::HHKOFMNJKDA
// Il2CppName: HHKOFMNJKDA
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::HHKOFMNJKDA)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "HHKOFMNJKDA", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::ODEEKFKBKMD
// Il2CppName: ODEEKFKBKMD
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::ODEEKFKBKMD)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "ODEEKFKBKMD", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::EHHCJJADDDH
// Il2CppName: EHHCJJADDDH
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::EHHCJJADDDH)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "EHHCJJADDDH", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::NHNOABLHEEJ
// Il2CppName: NHNOABLHEEJ
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::NHNOABLHEEJ)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "NHNOABLHEEJ", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::KCFODGDFLHL
// Il2CppName: KCFODGDFLHL
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::KCFODGDFLHL)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "KCFODGDFLHL", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::LLMONLBCLKC
// Il2CppName: LLMONLBCLKC
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::LLMONLBCLKC)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "LLMONLBCLKC", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::HAPOEOFLCFC
// Il2CppName: HAPOEOFLCFC
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::HAPOEOFLCFC)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "HAPOEOFLCFC", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::AOCHBOFKAKN
// Il2CppName: AOCHBOFKAKN
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::AOCHBOFKAKN)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "AOCHBOFKAKN", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::PJOIJIEDPMP
// Il2CppName: PJOIJIEDPMP
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::PJOIJIEDPMP)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "PJOIJIEDPMP", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::GCCKLLDCHKL
// Il2CppName: GCCKLLDCHKL
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::GCCKLLDCHKL)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "GCCKLLDCHKL", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::HABDJCEKMNH
// Il2CppName: HABDJCEKMNH
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::HABDJCEKMNH)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "HABDJCEKMNH", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::HDDLOBOJCDD
// Il2CppName: HDDLOBOJCDD
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::HDDLOBOJCDD)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "HDDLOBOJCDD", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::NBBNHDOBADH
// Il2CppName: NBBNHDOBADH
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::NBBNHDOBADH)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "NBBNHDOBADH", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::EFEDNMKDDGH
// Il2CppName: EFEDNMKDDGH
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::EFEDNMKDDGH)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "EFEDNMKDDGH", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::MPKPGNJNLBO
// Il2CppName: MPKPGNJNLBO
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::MPKPGNJNLBO)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "MPKPGNJNLBO", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::FOIKDPOMLLN
// Il2CppName: FOIKDPOMLLN
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::FOIKDPOMLLN)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "FOIKDPOMLLN", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::HCILFCAANII
// Il2CppName: HCILFCAANII
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::HCILFCAANII)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "HCILFCAANII", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::ENNBLNMHCDM
// Il2CppName: ENNBLNMHCDM
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::ENNBLNMHCDM)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "ENNBLNMHCDM", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::PMOIBHEEPKD
// Il2CppName: PMOIBHEEPKD
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::PMOIBHEEPKD)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "PMOIBHEEPKD", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::PGDINKGGFHI
// Il2CppName: PGDINKGGFHI
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::PGDINKGGFHI)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "PGDINKGGFHI", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::JPHEBENNLCB
// Il2CppName: JPHEBENNLCB
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::JPHEBENNLCB)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "JPHEBENNLCB", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::GGAFMPPDBOH
// Il2CppName: GGAFMPPDBOH
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::GGAFMPPDBOH)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "GGAFMPPDBOH", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::KFFLHHLFGID
// Il2CppName: KFFLHHLFGID
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::KFFLHHLFGID)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "KFFLHHLFGID", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::KLKNBEHJMLP
// Il2CppName: KLKNBEHJMLP
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::KLKNBEHJMLP)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "KLKNBEHJMLP", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::FMCOMKPJIML
// Il2CppName: FMCOMKPJIML
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::FMCOMKPJIML)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "FMCOMKPJIML", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::MMBJIKNCNGM
// Il2CppName: MMBJIKNCNGM
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::MMBJIKNCNGM)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "MMBJIKNCNGM", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::DetachedFromInterface
// Il2CppName: DetachedFromInterface
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::DetachedFromInterface)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "DetachedFromInterface", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::FixedUpdate
// Il2CppName: FixedUpdate
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::FixedUpdate)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "FixedUpdate", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::OpenContainerInventory
// Il2CppName: OpenContainerInventory
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::OpenContainerInventory)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "OpenContainerInventory", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::CloseContainerInventory
// Il2CppName: CloseContainerInventory
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::CloseContainerInventory)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "CloseContainerInventory", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::HICFANHNBBI
// Il2CppName: HICFANHNBBI
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::HICFANHNBBI)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "HICFANHNBBI", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: MagicalActual::CustomItemContainer::AttachedToInterface
// Il2CppName: AttachedToInterface
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::CustomItemContainer::*)()>(&MagicalActual::CustomItemContainer::AttachedToInterface)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::CustomItemContainer*), "AttachedToInterface", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
