// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: MagicalActual.PlayerCharacter
#include "MagicalActual/PlayerCharacter.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-properties.hpp"
#include "beatsaber-hook/shared/utils/il2cpp-utils-fields.hpp"
#include "beatsaber-hook/shared/utils/utils.h"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::IO
namespace System::IO {
  // Forward declaring type: BinaryWriter
  class BinaryWriter;
}
// Completed forward declares
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::MagicalActual::PlayerCharacter::$$c__DisplayClass339_0);
DEFINE_IL2CPP_ARG_TYPE(::MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*, "MagicalActual", "PlayerCharacter/<>c__DisplayClass339_0");
// Type namespace: MagicalActual
namespace MagicalActual {
  // Size: 0x12
  #pragma pack(push, 1)
  // Autogenerated type: MagicalActual.PlayerCharacter/<>c__DisplayClass339_0
  // [TokenAttribute] Offset: FFFFFFFF
  // [CompilerGeneratedAttribute] Offset: AD3958
  class PlayerCharacter::$$c__DisplayClass339_0 : public ::Il2CppObject {
    public:
    public:
    // public System.UInt16 MMPLHKEKHKI
    // Size: 0x2
    // Offset: 0x10
    uint16_t MMPLHKEKHKI;
    // Field size check
    static_assert(sizeof(uint16_t) == 0x2);
    public:
    // Creating conversion operator: operator uint16_t
    constexpr operator uint16_t() const noexcept {
      return MMPLHKEKHKI;
    }
    // Get instance field reference: public System.UInt16 MMPLHKEKHKI
    [[deprecated("Use field access instead!")]] uint16_t& dyn_MMPLHKEKHKI();
    // System.Void COFILGKEPMG(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57410
    void COFILGKEPMG(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void MOBADBLGAEB(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57450
    void MOBADBLGAEB(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void HCEMBJNPMAE(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57490
    void HCEMBJNPMAE(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void IFNFDNDNLBK(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E574D0
    void IFNFDNDNLBK(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void KODFNNNFFGC(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57510
    void KODFNNNFFGC(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void CDJCOKLHEAM(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57550
    void CDJCOKLHEAM(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void PJIBJNOGJBK(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57590
    void PJIBJNOGJBK(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void EIOFBMIMFFN(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E575D0
    void EIOFBMIMFFN(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void CNPEMPCJFEJ(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57610
    void CNPEMPCJFEJ(::System::IO::BinaryWriter* FFJEENIEPJH);
    // public System.Void .ctor()
    // Offset: 0x1E57650
    template<::il2cpp_utils::CreationType creationType = ::il2cpp_utils::CreationType::Temporary>
    static PlayerCharacter::$$c__DisplayClass339_0* New_ctor() {
      static auto ___internal__logger = ::Logger::get().WithContext("::MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::.ctor");
      return THROW_UNLESS((::il2cpp_utils::New<PlayerCharacter::$$c__DisplayClass339_0*, creationType>()));
    }
    // System.Void HNCKJDHAIDM(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57658
    void HNCKJDHAIDM(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void MLAFMBPDDOK(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57698
    void MLAFMBPDDOK(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void MKMBJAPLMOG(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E576D8
    void MKMBJAPLMOG(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void CIAILKIJIOM(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57718
    void CIAILKIJIOM(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void HGOKKKPMDNI(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57758
    void HGOKKKPMDNI(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void GMKNNCMHBCE(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57798
    void GMKNNCMHBCE(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void DACELAACEEI(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E577D8
    void DACELAACEEI(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void IMNPGOFDLCL(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57818
    void IMNPGOFDLCL(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void OCGDJHGKEHK(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57858
    void OCGDJHGKEHK(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void BLMFFDBLJOK(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57898
    void BLMFFDBLJOK(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void FKEOMBHLLBF(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E578D8
    void FKEOMBHLLBF(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void CKBJDMFOPAK(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57918
    void CKBJDMFOPAK(::System::IO::BinaryWriter* FFJEENIEPJH);
    // System.Void GKCCDBNPDGL(System.IO.BinaryWriter FFJEENIEPJH)
    // Offset: 0x1E57958
    void GKCCDBNPDGL(::System::IO::BinaryWriter* FFJEENIEPJH);
  }; // MagicalActual.PlayerCharacter/<>c__DisplayClass339_0
  #pragma pack(pop)
  static check_size<sizeof(PlayerCharacter::$$c__DisplayClass339_0), 16 + sizeof(uint16_t)> __MagicalActual_PlayerCharacter_$$c__DisplayClass339_0SizeCheck;
  static_assert(sizeof(PlayerCharacter::$$c__DisplayClass339_0) == 0x12);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::COFILGKEPMG
// Il2CppName: COFILGKEPMG
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::COFILGKEPMG)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "COFILGKEPMG", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::MOBADBLGAEB
// Il2CppName: MOBADBLGAEB
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::MOBADBLGAEB)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "MOBADBLGAEB", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::HCEMBJNPMAE
// Il2CppName: HCEMBJNPMAE
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::HCEMBJNPMAE)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "HCEMBJNPMAE", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::IFNFDNDNLBK
// Il2CppName: IFNFDNDNLBK
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::IFNFDNDNLBK)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "IFNFDNDNLBK", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::KODFNNNFFGC
// Il2CppName: KODFNNNFFGC
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::KODFNNNFFGC)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "KODFNNNFFGC", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::CDJCOKLHEAM
// Il2CppName: CDJCOKLHEAM
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::CDJCOKLHEAM)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "CDJCOKLHEAM", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::PJIBJNOGJBK
// Il2CppName: PJIBJNOGJBK
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::PJIBJNOGJBK)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "PJIBJNOGJBK", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::EIOFBMIMFFN
// Il2CppName: EIOFBMIMFFN
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::EIOFBMIMFFN)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "EIOFBMIMFFN", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::CNPEMPCJFEJ
// Il2CppName: CNPEMPCJFEJ
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::CNPEMPCJFEJ)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "CNPEMPCJFEJ", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::New_ctor
// Il2CppName: .ctor
// Cannot get method pointer of value based method overload from template for constructor!
// Try using FindMethod instead!
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::HNCKJDHAIDM
// Il2CppName: HNCKJDHAIDM
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::HNCKJDHAIDM)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "HNCKJDHAIDM", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::MLAFMBPDDOK
// Il2CppName: MLAFMBPDDOK
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::MLAFMBPDDOK)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "MLAFMBPDDOK", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::MKMBJAPLMOG
// Il2CppName: MKMBJAPLMOG
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::MKMBJAPLMOG)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "MKMBJAPLMOG", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::CIAILKIJIOM
// Il2CppName: CIAILKIJIOM
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::CIAILKIJIOM)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "CIAILKIJIOM", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::HGOKKKPMDNI
// Il2CppName: HGOKKKPMDNI
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::HGOKKKPMDNI)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "HGOKKKPMDNI", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::GMKNNCMHBCE
// Il2CppName: GMKNNCMHBCE
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::GMKNNCMHBCE)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "GMKNNCMHBCE", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::DACELAACEEI
// Il2CppName: DACELAACEEI
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::DACELAACEEI)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "DACELAACEEI", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::IMNPGOFDLCL
// Il2CppName: IMNPGOFDLCL
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::IMNPGOFDLCL)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "IMNPGOFDLCL", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::OCGDJHGKEHK
// Il2CppName: OCGDJHGKEHK
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::OCGDJHGKEHK)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "OCGDJHGKEHK", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::BLMFFDBLJOK
// Il2CppName: BLMFFDBLJOK
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::BLMFFDBLJOK)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "BLMFFDBLJOK", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::FKEOMBHLLBF
// Il2CppName: FKEOMBHLLBF
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::FKEOMBHLLBF)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "FKEOMBHLLBF", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::CKBJDMFOPAK
// Il2CppName: CKBJDMFOPAK
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::CKBJDMFOPAK)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "CKBJDMFOPAK", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
// Writing MetadataGetter for method: MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::GKCCDBNPDGL
// Il2CppName: GKCCDBNPDGL
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<void (MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::*)(::System::IO::BinaryWriter*)>(&MagicalActual::PlayerCharacter::$$c__DisplayClass339_0::GKCCDBNPDGL)> {
  static const MethodInfo* get() {
    static auto* FFJEENIEPJH = &::il2cpp_utils::GetClassFromName("System.IO", "BinaryWriter")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(MagicalActual::PlayerCharacter::$$c__DisplayClass339_0*), "GKCCDBNPDGL", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{FFJEENIEPJH});
  }
};
