// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: System.Enum
#include "System/Enum.hpp"
// Completed includes
// Type namespace: 
namespace GlobalNamespace {
  // Forward declaring type: vx_sessiongroup_playback_mode
  struct vx_sessiongroup_playback_mode;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
DEFINE_IL2CPP_ARG_TYPE(::GlobalNamespace::vx_sessiongroup_playback_mode, "", "vx_sessiongroup_playback_mode");
// Type namespace: 
namespace GlobalNamespace {
  // Size: 0x4
  #pragma pack(push, 1)
  // Autogenerated type: vx_sessiongroup_playback_mode
  // [TokenAttribute] Offset: FFFFFFFF
  struct vx_sessiongroup_playback_mode/*, public ::System::Enum*/ {
    public:
    public:
    // public System.Int32 value__
    // Size: 0x4
    // Offset: 0x0
    int value;
    // Field size check
    static_assert(sizeof(int) == 0x4);
    public:
    // Creating value type constructor for type: vx_sessiongroup_playback_mode
    constexpr vx_sessiongroup_playback_mode(int value_ = {}) noexcept : value{value_} {}
    // Creating interface conversion operator: operator ::System::Enum
    operator ::System::Enum() noexcept {
      return *reinterpret_cast<::System::Enum*>(this);
    }
    // Creating conversion operator: operator int
    constexpr operator int() const noexcept {
      return value;
    }
    // static field const value: static public vx_sessiongroup_playback_mode VX_SESSIONGROUP_PLAYBACK_MODE_NORMAL
    static constexpr const int VX_SESSIONGROUP_PLAYBACK_MODE_NORMAL = 0;
    // Get static field: static public vx_sessiongroup_playback_mode VX_SESSIONGROUP_PLAYBACK_MODE_NORMAL
    static ::GlobalNamespace::vx_sessiongroup_playback_mode _get_VX_SESSIONGROUP_PLAYBACK_MODE_NORMAL();
    // Set static field: static public vx_sessiongroup_playback_mode VX_SESSIONGROUP_PLAYBACK_MODE_NORMAL
    static void _set_VX_SESSIONGROUP_PLAYBACK_MODE_NORMAL(::GlobalNamespace::vx_sessiongroup_playback_mode value);
    // static field const value: static public vx_sessiongroup_playback_mode VX_SESSIONGROUP_PLAYBACK_MODE_VOX
    static constexpr const int VX_SESSIONGROUP_PLAYBACK_MODE_VOX = 1;
    // Get static field: static public vx_sessiongroup_playback_mode VX_SESSIONGROUP_PLAYBACK_MODE_VOX
    static ::GlobalNamespace::vx_sessiongroup_playback_mode _get_VX_SESSIONGROUP_PLAYBACK_MODE_VOX();
    // Set static field: static public vx_sessiongroup_playback_mode VX_SESSIONGROUP_PLAYBACK_MODE_VOX
    static void _set_VX_SESSIONGROUP_PLAYBACK_MODE_VOX(::GlobalNamespace::vx_sessiongroup_playback_mode value);
    // Get instance field reference: public System.Int32 value__
    [[deprecated("Use field access instead!")]] int& dyn_value__();
  }; // vx_sessiongroup_playback_mode
  #pragma pack(pop)
  static check_size<sizeof(vx_sessiongroup_playback_mode), 0 + sizeof(int)> __GlobalNamespace_vx_sessiongroup_playback_modeSizeCheck;
  static_assert(sizeof(vx_sessiongroup_playback_mode) == 0x4);
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
