// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/byref.hpp"
// Including type: VivoxUnity.IKeyedItemNotifyPropertyChanged`1
#include "VivoxUnity/IKeyedItemNotifyPropertyChanged_1.hpp"
#include "beatsaber-hook/shared/utils/typedefs-string.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System
namespace System {
  // Forward declaring type: DateTime
  struct DateTime;
}
// Completed forward declares
// Type namespace: VivoxUnity
namespace VivoxUnity {
  // Forward declaring type: ITextMessage
  class ITextMessage;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::VivoxUnity::ITextMessage);
DEFINE_IL2CPP_ARG_TYPE(::VivoxUnity::ITextMessage*, "VivoxUnity", "ITextMessage");
// Type namespace: VivoxUnity
namespace VivoxUnity {
  // Size: 0x0
  #pragma pack(push, 1)
  // Autogenerated type: VivoxUnity.ITextMessage
  // [TokenAttribute] Offset: FFFFFFFF
  class ITextMessage/*, public ::VivoxUnity::IKeyedItemNotifyPropertyChanged_1<::StringW>*/ {
    public:
    // Creating interface conversion operator: operator ::VivoxUnity::IKeyedItemNotifyPropertyChanged_1<::StringW>
    operator ::VivoxUnity::IKeyedItemNotifyPropertyChanged_1<::StringW>() noexcept {
      return *reinterpret_cast<::VivoxUnity::IKeyedItemNotifyPropertyChanged_1<::StringW>*>(this);
    }
    // public System.DateTime get_ReceivedTime()
    // Offset: 0xFFFFFFFFFFFFFFFF
    ::System::DateTime get_ReceivedTime();
    // public System.String get_Message()
    // Offset: 0xFFFFFFFFFFFFFFFF
    ::StringW get_Message();
    // public System.String get_Language()
    // Offset: 0xFFFFFFFFFFFFFFFF
    ::StringW get_Language();
  }; // VivoxUnity.ITextMessage
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: VivoxUnity::ITextMessage::get_ReceivedTime
// Il2CppName: get_ReceivedTime
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::DateTime (VivoxUnity::ITextMessage::*)()>(&VivoxUnity::ITextMessage::get_ReceivedTime)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(VivoxUnity::ITextMessage*), "get_ReceivedTime", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: VivoxUnity::ITextMessage::get_Message
// Il2CppName: get_Message
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (VivoxUnity::ITextMessage::*)()>(&VivoxUnity::ITextMessage::get_Message)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(VivoxUnity::ITextMessage*), "get_Message", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
// Writing MetadataGetter for method: VivoxUnity::ITextMessage::get_Language
// Il2CppName: get_Language
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::StringW (VivoxUnity::ITextMessage::*)()>(&VivoxUnity::ITextMessage::get_Language)> {
  static const MethodInfo* get() {
    return ::il2cpp_utils::FindMethod(classof(VivoxUnity::ITextMessage*), "get_Language", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{});
  }
};
