// Autogenerated from CppHeaderCreator
// Created by Sc2ad
// =========================================================================
#pragma once
// Begin includes
#include "beatsaber-hook/shared/utils/typedefs.h"
#include "beatsaber-hook/shared/utils/byref.hpp"
// Completed includes
// Begin forward declares
// Forward declaring namespace: System::Collections::Generic
namespace System::Collections::Generic {
  // Forward declaring type: List`1<T>
  template<typename T>
  class List_1;
}
// Forward declaring namespace: UnityEngine
namespace UnityEngine {
  // Forward declaring type: GameObject
  class GameObject;
}
// Forward declaring namespace: UnityEngine::UI
namespace UnityEngine::UI {
  // Forward declaring type: Image
  class Image;
}
// Completed forward declares
// Type namespace: Tayx.Graphy.Utils
namespace Tayx::Graphy::Utils {
  // Forward declaring type: ExtensionMethods
  class ExtensionMethods;
}
#include "beatsaber-hook/shared/utils/il2cpp-type-check.hpp"
NEED_NO_BOX(::Tayx::Graphy::Utils::ExtensionMethods);
DEFINE_IL2CPP_ARG_TYPE(::Tayx::Graphy::Utils::ExtensionMethods*, "Tayx.Graphy.Utils", "ExtensionMethods");
// Type namespace: Tayx.Graphy.Utils
namespace Tayx::Graphy::Utils {
  // Size: 0x10
  #pragma pack(push, 1)
  // Autogenerated type: Tayx.Graphy.Utils.ExtensionMethods
  // [TokenAttribute] Offset: FFFFFFFF
  // [ExtensionAttribute] Offset: FFFFFFFF
  class ExtensionMethods : public ::Il2CppObject {
    public:
    // static public System.Collections.Generic.List`1<UnityEngine.GameObject> SetAllActive(System.Collections.Generic.List`1<UnityEngine.GameObject> gameObjects, System.Boolean active)
    // Offset: 0x1042AC4
    static ::System::Collections::Generic::List_1<::UnityEngine::GameObject*>* SetAllActive(::System::Collections::Generic::List_1<::UnityEngine::GameObject*>* gameObjects, bool active);
    // static public System.Collections.Generic.List`1<UnityEngine.UI.Image> SetOneActive(System.Collections.Generic.List`1<UnityEngine.UI.Image> images, System.Int32 active)
    // Offset: 0x1042C68
    static ::System::Collections::Generic::List_1<::UnityEngine::UI::Image*>* SetOneActive(::System::Collections::Generic::List_1<::UnityEngine::UI::Image*>* images, int active);
    // static public System.Collections.Generic.List`1<UnityEngine.UI.Image> SetAllActive(System.Collections.Generic.List`1<UnityEngine.UI.Image> images, System.Boolean active)
    // Offset: 0x10404FC
    static ::System::Collections::Generic::List_1<::UnityEngine::UI::Image*>* SetAllActive(::System::Collections::Generic::List_1<::UnityEngine::UI::Image*>* images, bool active);
  }; // Tayx.Graphy.Utils.ExtensionMethods
  #pragma pack(pop)
}
#include "beatsaber-hook/shared/utils/il2cpp-utils-methods.hpp"
// Writing MetadataGetter for method: Tayx::Graphy::Utils::ExtensionMethods::SetAllActive
// Il2CppName: SetAllActive
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Collections::Generic::List_1<::UnityEngine::GameObject*>* (*)(::System::Collections::Generic::List_1<::UnityEngine::GameObject*>*, bool)>(&Tayx::Graphy::Utils::ExtensionMethods::SetAllActive)> {
  static const MethodInfo* get() {
    static auto* gameObjects = &::il2cpp_utils::MakeGeneric(::il2cpp_utils::GetClassFromName("System.Collections.Generic", "List`1"), ::std::vector<const Il2CppClass*>{::il2cpp_utils::GetClassFromName("UnityEngine", "GameObject")})->byval_arg;
    static auto* active = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Tayx::Graphy::Utils::ExtensionMethods*), "SetAllActive", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{gameObjects, active});
  }
};
// Writing MetadataGetter for method: Tayx::Graphy::Utils::ExtensionMethods::SetOneActive
// Il2CppName: SetOneActive
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Collections::Generic::List_1<::UnityEngine::UI::Image*>* (*)(::System::Collections::Generic::List_1<::UnityEngine::UI::Image*>*, int)>(&Tayx::Graphy::Utils::ExtensionMethods::SetOneActive)> {
  static const MethodInfo* get() {
    static auto* images = &::il2cpp_utils::MakeGeneric(::il2cpp_utils::GetClassFromName("System.Collections.Generic", "List`1"), ::std::vector<const Il2CppClass*>{::il2cpp_utils::GetClassFromName("UnityEngine.UI", "Image")})->byval_arg;
    static auto* active = &::il2cpp_utils::GetClassFromName("System", "Int32")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Tayx::Graphy::Utils::ExtensionMethods*), "SetOneActive", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{images, active});
  }
};
// Writing MetadataGetter for method: Tayx::Graphy::Utils::ExtensionMethods::SetAllActive
// Il2CppName: SetAllActive
template<>
struct ::il2cpp_utils::il2cpp_type_check::MetadataGetter<static_cast<::System::Collections::Generic::List_1<::UnityEngine::UI::Image*>* (*)(::System::Collections::Generic::List_1<::UnityEngine::UI::Image*>*, bool)>(&Tayx::Graphy::Utils::ExtensionMethods::SetAllActive)> {
  static const MethodInfo* get() {
    static auto* images = &::il2cpp_utils::MakeGeneric(::il2cpp_utils::GetClassFromName("System.Collections.Generic", "List`1"), ::std::vector<const Il2CppClass*>{::il2cpp_utils::GetClassFromName("UnityEngine.UI", "Image")})->byval_arg;
    static auto* active = &::il2cpp_utils::GetClassFromName("System", "Boolean")->byval_arg;
    return ::il2cpp_utils::FindMethod(classof(Tayx::Graphy::Utils::ExtensionMethods*), "SetAllActive", std::vector<Il2CppClass*>(), ::std::vector<const Il2CppType*>{images, active});
  }
};
